# Generated by Django 4.2.7 on 2023-11-22 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('request_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления запроса')),
                ('response_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения ответа')),
                ('path', models.CharField(max_length=250, verbose_name='URL адрес')),
                ('query_params', models.TextField(blank=True, null=True, verbose_name='Параметры запроса')),
                ('request_method', models.CharField(max_length=10, verbose_name='Метод запроса')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Код ответа')),
            ],
            options={
                'verbose_name': 'API запрос',
                'verbose_name_plural': 'Журнал запросов к API',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь (Телеграм бот)',
                'verbose_name_plural': 'Пользователи (Телеграм бот)',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_msg', models.TextField(verbose_name='Сообщение от пользователя')),
                ('response_msg', models.TextField(verbose_name='Ответное сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение (Телеграм бот)',
                'verbose_name_plural': 'Сообщения (Телеграм бот)',
            },
        ),
    ]
